; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
src_dir = .

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32dev
framework = arduino
; platform_packages =
    ; platformio/toolchain-xtensa-esp-elf@14.2.0+20241119
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_flags = 
	-DCONFIG_BT_ACL_CONNECTIONS=4
	-DCONFIG_GATTC_MAX_CONNECTIONS=2
	-Wno-macro-redefined
upload_speed = 921600
board_build.partitions = default.csv
board_build.filesystem = none
build_src_filter =
  +<*.ino>
  +<*.cpp>
  +<*.c>
  -<.git/>
  -<.pio/>
  -<.vscode/>
  -<test/>
  -<data/>
upload_port = COM12