; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
src_dir = .

[env:esp32dev]
extra_scripts = pre:load_env.py
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32dev
framework = arduino
; platform_packages =
    ; platformio/toolchain-xtensa-esp-elf@14.2.0+20241119
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.embed_files = 
	sdkconfig.defaults
build_flags = 
	-DCONFIG_BT_ACL_CONNECTIONS=4
	-DCONFIG_GATTC_MAX_CONNECTIONS=2
	-DCONFIG_FREERTOS_MAX_TASK_NAME_LEN=16
	-DCONFIG_FREERTOS_TASK_NOTIFICATION_ARRAY_ENTRIES=1
	-DCONFIG_LOG_DEFAULT_LEVEL=3
	-DCONFIG_LOG_MAXIMUM_LEVEL=5
	-DCONFIG_LWIP_IPV6=1
	-DCONFIG_BT_ENABLED=1
	-DCONFIG_BT_CLASSIC_ENABLED=1
	-DCONFIG_BT_SPP_ENABLED=1
	-DCONFIG_BTDM_CTRL_MODE_BTDM=1
	-DCONFIG_BLUEDROID_ENABLED=1
	-DCONFIG_BT_BLUEDROID_ENABLED=1
	-DLOG_FORMAT_DETAILED=0
	-Wno-error=deprecated-declarations
	-Wno-macro-redefined
upload_speed = 921600
lib_deps = 
	;BLE library is built-in to framework
upload_port = COM9
board_build.partitions = default.csv
board_build.filesystem = none
build_src_filter =
  +<*.ino>
  +<*.cpp>
  +<*.c>
  -<.git/>
  -<.pio/>
  -<.vscode/>
  -<test/>
  -<data/>
  -<*.md>
  -<*.example>